@Library('shared-library') _
// 範例 Jenkinsfile
pipeline {
    agent any
    stages{
        stage('test library'){
            steps{
                test('Ithome')
                test('Jenkins')
                test('Ben')            
            }
        }
    }
}
