@Library('test_groovy_library') _
// 範例 Jenkinsfile
pipeline {
    agent any
    stages{
        stage('test library'){
            steps{
                sample('Ithome')
                sample('Jenkins')
                sample('Ben')            
            }
        }
    }
}
